checks:
  doNotAutoAddDefaults: true
#   include:
#   - dangling-service
#   - default-service-account
#   - deprecated-service-account-field
#   - env-var-secret
#   - mismatching-selector
#   - no-anti-affinity
#   - no-extensions-v1beta
#   - no-liveness-probe
#   - no-read-only-root-fs
#   - no-readiness-probe
#   - non-existent-service-account
#   - privileged-container
#   - required-annotation-email 
#   - required-label-owner
#   - run-as-non-root
#   - ssh-port
#   - unset-cpu-requirements
#   - unset-memory-requirements
#   - writable-host-mount